#define DUMMY_ENABLED 1
#define DUMMY_PROB_PCT 25
#define JITTER_SEC 2
#define ADAPTIVE_MODE 1
#define ADAPTIVE_WINDOW_SEC 60
#define ADAPTIVE_TARGET_REAL_TX 8
#define ADAPTIVE_DUMMY_PROB_MIN_PCT 8
#define ADAPTIVE_DUMMY_PROB_MAX_PCT 35
#define ADAPTIVE_EPSILON_MIN_MILLI 600
#define ADAPTIVE_EPSILON_MAX_MILLI 2000
#include "udp-client-mix.c"
